version: '3.8'
services:
  dex:
    image: dexidp/dex
    container_name: dex
    ports:
      - "5556:5556"
    volumes:
      - ./dex-config.yaml:/etc/dex/config.docker.yaml
    command: ["dex", "serve", "/etc/dex/config.docker.yaml"]
